apiVersion: apps/v1
kind: Deployment

metadata:
  name: rms-deployment
  namespace: rent-management-system

spec:
  replicas: 1

  selector:
    matchLabels:
      app: rms

  template:
    metadata:
      labels:
        app: rms

    spec:
      containers:
        - name: rms

          image: nischaldev31/rent-management-system:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: rms-config

            - secretRef:
                name: rms-secret