apiVersion: v1
kind: Service

metadata:
  name: rms-service
  namespace: rent-management-system

spec:
  selector:
    app: rms

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 31362

  type: NodePort