apiVersion: v1
kind: Secret

metadata:
  name: rms-secret
  namespace: rent-management-system

type: Opaque

stringData:
  SECRET_KEY: "CHANGE_ME"
  DATABASE_URL: "CHANGE_ME"
  EMAIL_HOST_PASSWORD: "CHANGE_ME"
  GOOGLE_SECRET: "CHANGE_ME"
  TWILIO_ACCOUNT_SID: "CHANGE_ME"
  TWILIO_AUTH_TOKEN: "CHANGE_ME"
  SUPERUSER_USERNAME: "admin"
  SUPERUSER_EMAIL: "admin1@gmail.com"
  SUPERUSER_PASSWORD: "CHANGE_ME"