apiVersion: v1
kind: Secret

metadata:
  name: rms-secret
  namespace: rent-management-system

type: Opaque

stringData:
  SECRET_KEY: "REPLACE_WITH_NEW_DJANGO_SECRET_KEY"

  DATABASE_URL: "postgresql://admin:rmspass@postgres:5432/rms_db"

  EMAIL_HOST_PASSWORD: "REPLACE_WITH_NEW_GMAIL_APP_PASSWORD"

  GOOGLE_SECRET: "REPLACE_WITH_NEW_GOOGLE_CLIENT_SECRET"

  TWILIO_ACCOUNT_SID: "REPLACE_WITH_TWILIO_ACCOUNT_SID"

  TWILIO_AUTH_TOKEN: "REPLACE_WITH_TWILIO_AUTH_TOKEN"

  SUPERUSER_USERNAME: "adminbikash"

  SUPERUSER_EMAIL: "bikashgosain0@gmail.com"

  SUPERUSER_PASSWORD: "REPLACE_WITH_STRONG_SUPERUSER_PASSWORD"