apiVersion: v1
kind: Secret
metadata:
  name: bidforge-secret
  namespace: bidforge
type: Opaque
stringData:
  SECRET_KEY: "django-insecure-dev-key-change-later"
  DATABASE_URL: "postgresql://bidforge:bidforgepassword@postgres:5432/bidforge"
  DJANGO_SUPERUSER_EMAIL: "admin@gmail.com"
  DJANGO_SUPERUSER_PASSWORD: "admin"